name: hello-goodbye-list-edition
on:
    workflow_dispatch:
        inputs:
            helloWhere:
                description: 'Who do you want to say hello to?'
                required: true
                default: 'world'
                type: choice
                options:
                - world
                - beard
                - breton
                - everyone
            goodbyeWhere:
                description: 'Who do you want to say goodbye to?'
                default: 'world'
                type: choice
                options:
                - world
                - beard
                - breton
                - everyone
jobs:
    hello:
        runs-on: larger-32
        steps:
        - run: echo "Hello ${{ github.event.inputs.helloWhere }}"
    goodbye:
        runs-on: larger-32
        steps:
        - run: echo "Goodbye ${{ github.event.inputs.goodbyeWhere }}"
        needs: hello
