hello-goodbye
name: hello-goodbye
on:
  push:
jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
     - run: echo "Hello world"
  goodbye:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Goodbye world"
